name: student_portal_app
description: Student Portal Mobile Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0
  http: ^1.2.2
  fl_chart: ^0.69.0
  intl: ^0.19.0
  local_auth: ^2.3.0
  crypto: ^3.0.5
  image_picker: ^1.1.2
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
